'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class AdminAnnouncements
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents pnlHeader As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlLogo As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblCampus As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblCare As Global.System.Web.UI.WebControls.Label
    Protected WithEvents pnlHeaderRight As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblAdminPortal As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lnkDashboardTop As Global.System.Web.UI.WebControls.HyperLink
    Protected WithEvents pnlContainer As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlPageHeading As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblSmallTitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblPageTitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblPageSubtitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents pnlFormCard As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblFormTitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblFormIntro As Global.System.Web.UI.WebControls.Label
    Protected WithEvents vsAnnouncement As Global.System.Web.UI.WebControls.ValidationSummary
    Protected WithEvents pnlTitleGroup As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents txtTitle As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents rfvTitle As Global.System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents pnlDescriptionGroup As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblDescription As Global.System.Web.UI.WebControls.Label
    Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents rfvDescription As Global.System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents btnPost As Global.System.Web.UI.WebControls.Button
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
    Protected WithEvents pnlSectionHeading As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblSectionTitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblSectionText As Global.System.Web.UI.WebControls.Label
    Protected WithEvents pnlTableCard As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents gvAnnouncements As Global.System.Web.UI.WebControls.GridView
    Protected WithEvents pnlFooterArea As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lnkBack As Global.System.Web.UI.WebControls.HyperLink
End Class