'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class AdminComplaints

    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    Protected WithEvents pnlHeader As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents pnlLogo As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents lblCampus As Global.System.Web.UI.WebControls.Label

    Protected WithEvents lblCare As Global.System.Web.UI.WebControls.Label

    Protected WithEvents pnlHeaderRight As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents lblAdminPortal As Global.System.Web.UI.WebControls.Label

    Protected WithEvents lnkDashboardTop As Global.System.Web.UI.WebControls.HyperLink

    Protected WithEvents pnlContainer As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents pnlPageHeader As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents lblSmallTitle As Global.System.Web.UI.WebControls.Label

    Protected WithEvents lblPageTitle As Global.System.Web.UI.WebControls.Label

    Protected WithEvents lblDescription As Global.System.Web.UI.WebControls.Label

    Protected WithEvents pnlFilterBox As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents lblViewing As Global.System.Web.UI.WebControls.Label

    Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

    Protected WithEvents pnlTableCard As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents gvComplaints As Global.System.Web.UI.WebControls.GridView

    Protected WithEvents pnlFooterArea As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents lnkBack As Global.System.Web.UI.WebControls.HyperLink

End Class