'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class AdminDashboard

    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents pnlHeader As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlLogo As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblCampus As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblCare As Global.System.Web.UI.WebControls.Label
    Protected WithEvents pnlHeaderRight As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblAdminPortal As Global.System.Web.UI.WebControls.Label
    Protected WithEvents btnLogout As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents pnlContainer As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlWelcomeBanner As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlWelcomeContent As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblDashboardType As Global.System.Web.UI.WebControls.Label
    Protected WithEvents pnlWelcomeTitle As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblWelcomeText As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblAdminName As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblExclamation As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblWelcomeDescription As Global.System.Web.UI.WebControls.Label
    Protected WithEvents pnlIssueOverviewHeading As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblIssueOverviewTitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents pnlStats As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlTotalIssues As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlTotalTop As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblTotalTitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblTotalCount As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lnkAllIssues As Global.System.Web.UI.WebControls.HyperLink
    Protected WithEvents pnlPendingIssues As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlPendingTop As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblPendingTitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblPendingCount As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lnkPendingIssues As Global.System.Web.UI.WebControls.HyperLink
    Protected WithEvents pnlProgressIssues As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlProgressTop As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblProgressTitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblProgressCount As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lnkProgressIssues As Global.System.Web.UI.WebControls.HyperLink
    Protected WithEvents pnlResolvedIssues As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlResolvedTop As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblResolvedTitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblResolvedCount As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lnkResolvedIssues As Global.System.Web.UI.WebControls.HyperLink
    Protected WithEvents pnlManagementHeading As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblManagementTitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblManagementText As Global.System.Web.UI.WebControls.Label
    Protected WithEvents pnlManagementGrid As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlManageIssues As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblManageIssuesTitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblManageIssuesText As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lnkManageIssues As Global.System.Web.UI.WebControls.HyperLink
    Protected WithEvents pnlManageAnnouncements As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblManageAnnouncementsTitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblManageAnnouncementsText As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lnkManageAnnouncements As Global.System.Web.UI.WebControls.HyperLink
    Protected WithEvents lblFooter As Global.System.Web.UI.WebControls.Label

End Class