'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class Complaint
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents pnlHeader As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlLogo As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblCampus As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblCare As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lnkDashboardTop As Global.System.Web.UI.WebControls.HyperLink
    Protected WithEvents pnlPage As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlPageHeading As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblSmallTitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblPageTitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblPageSubtitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents pnlContent As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlFormCard As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents vsComplaint As Global.System.Web.UI.WebControls.ValidationSummary
    Protected WithEvents pnlTitleGroup As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblIssueTitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents txtTitle As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents rfvTitle As Global.System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents pnlCategoryGroup As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblCategory As Global.System.Web.UI.WebControls.Label
    Protected WithEvents ddlCategory As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents rfvCategory As Global.System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents pnlDescriptionGroup As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblDescription As Global.System.Web.UI.WebControls.Label
    Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents rfvDescription As Global.System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents pnlLocationGroup As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblLocation As Global.System.Web.UI.WebControls.Label
    Protected WithEvents txtLocation As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents rfvLocation As Global.System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
End Class