'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class Dashboard
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents pnlHeader As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlLogo As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblCampus As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblCare As Global.System.Web.UI.WebControls.Label
    Protected WithEvents pnlHeaderRight As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblStudentPortal As Global.System.Web.UI.WebControls.Label
    Protected WithEvents btnLogout As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents pnlContainer As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlWelcomeBanner As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlWelcomeContent As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblDashboardType As Global.System.Web.UI.WebControls.Label
    Protected WithEvents pnlWelcomeTitle As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblWelcomeText As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblUserName As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblExclamation As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblTagline As Global.System.Web.UI.WebControls.Label
    Protected WithEvents pnlSectionHeading As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblSectionTitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblSectionText As Global.System.Web.UI.WebControls.Label
    Protected WithEvents pnlCards As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlRaiseIssue As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblRaiseIssueTitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblRaiseIssueText As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lnkRaiseIssue As Global.System.Web.UI.WebControls.HyperLink
    Protected WithEvents pnlMyIssues As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblMyIssuesTitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblMyIssuesText As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lnkMyIssues As Global.System.Web.UI.WebControls.HyperLink
    Protected WithEvents pnlAnnouncements As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblAnnouncementsTitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblAnnouncementsText As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lnkAnnouncements As Global.System.Web.UI.WebControls.HyperLink
    Protected WithEvents lblFooter As Global.System.Web.UI.WebControls.Label
End Class