'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class CampusConnectLogin
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents pnlPage As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlLoginWrapper As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlBrand As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblBrandName As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblBrandTagline As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblBrandDescription As Global.System.Web.UI.WebControls.Label
    Protected WithEvents pnlLogin As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblSmallTitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblPageTitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblSubtitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents vsLogin As Global.System.Web.UI.WebControls.ValidationSummary
    Protected WithEvents pnlEmailGroup As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblEmail As Global.System.Web.UI.WebControls.Label
    Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents rfvEmail As Global.System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents revEmail As Global.System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents pnlPasswordGroup As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblPassword As Global.System.Web.UI.WebControls.Label
    Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents rfvPassword As Global.System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents pnlRememberArea As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents chkRememberEmail As Global.System.Web.UI.WebControls.CheckBox
    Protected WithEvents btnLogin As Global.System.Web.UI.WebControls.Button
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
    Protected WithEvents pnlSignupArea As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblSignupText As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lnkSignup As Global.System.Web.UI.WebControls.HyperLink
End Class