'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class MyComplaints

    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    Protected WithEvents pnlHeader As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents pnlLogo As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents lblCampus As Global.System.Web.UI.WebControls.Label

    Protected WithEvents lblCare As Global.System.Web.UI.WebControls.Label

    Protected WithEvents lnkDashboardTop As Global.System.Web.UI.WebControls.HyperLink

    Protected WithEvents pnlContainer As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents pnlPageHeader As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents pnlPageHeadingLeft As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents lblSmallTitle As Global.System.Web.UI.WebControls.Label

    Protected WithEvents lblPageTitle As Global.System.Web.UI.WebControls.Label

    Protected WithEvents lblWelcome As Global.System.Web.UI.WebControls.Label

    Protected WithEvents pnlRaiseIssueAction As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents lnkRaiseNewIssue As Global.System.Web.UI.WebControls.HyperLink

    Protected WithEvents pnlInfoBar As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents lblInfoTitle As Global.System.Web.UI.WebControls.Label

    Protected WithEvents lblInfoText As Global.System.Web.UI.WebControls.Label

    Protected WithEvents pnlTableCard As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents gvComplaints As Global.System.Web.UI.WebControls.GridView

    Protected WithEvents pnlFooterArea As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents lnkDashboard As Global.System.Web.UI.WebControls.HyperLink

End Class