'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class Signup
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents pnlPage As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlSignupWrapper As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlBrand As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblBrandName As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblBrandTagline As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblBrandDescription As Global.System.Web.UI.WebControls.Label
    Protected WithEvents pnlSignup As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblSmallTitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblPageTitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblSubtitle As Global.System.Web.UI.WebControls.Label
    Protected WithEvents vsSignup As Global.System.Web.UI.WebControls.ValidationSummary
    Protected WithEvents pnlNameGroup As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblName As Global.System.Web.UI.WebControls.Label
    Protected WithEvents txtName As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents rfvName As Global.System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents pnlEmailGroup As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblEmail As Global.System.Web.UI.WebControls.Label
    Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents rfvEmail As Global.System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents revEmail As Global.System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents pnlPasswordGroup As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblPassword As Global.System.Web.UI.WebControls.Label
    Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents rfvPassword As Global.System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents pnlConfirmPasswordGroup As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblConfirmPassword As Global.System.Web.UI.WebControls.Label
    Protected WithEvents txtConfirmPassword As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents rfvConfirmPassword As Global.System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents cvPassword As Global.System.Web.UI.WebControls.CompareValidator
    Protected WithEvents pnlDepartmentGroup As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblDepartment As Global.System.Web.UI.WebControls.Label
    Protected WithEvents txtDepartment As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents rfvDepartment As Global.System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents pnlYearGroup As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblYear As Global.System.Web.UI.WebControls.Label
    Protected WithEvents txtYear As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents rfvYear As Global.System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents rvYear As Global.System.Web.UI.WebControls.RangeValidator
    Protected WithEvents btnSignup As Global.System.Web.UI.WebControls.Button
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
    Protected WithEvents pnlLoginArea As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lblLoginText As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lnkLogin As Global.System.Web.UI.WebControls.HyperLink
End Class