'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class WebServiceDashboard

    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    Protected WithEvents lblTotal As Global.System.Web.UI.WebControls.Label

    Protected WithEvents lblPending As Global.System.Web.UI.WebControls.Label

    Protected WithEvents lblInProgress As Global.System.Web.UI.WebControls.Label

    Protected WithEvents lblResolved As Global.System.Web.UI.WebControls.Label

    Protected WithEvents btnRefresh As Global.System.Web.UI.WebControls.Button

    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

End Class