'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace CampusCareWebService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="CampusCareServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class CampusCareService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetTotalIssuesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetPendingIssuesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetInProgressIssuesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetResolvedIssuesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.CampusConnect.My.MySettings.Default.CampusConnect_CampusCareWebService_CampusCareService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetTotalIssuesCompleted As GetTotalIssuesCompletedEventHandler
        
        '''<remarks/>
        Public Event GetPendingIssuesCompleted As GetPendingIssuesCompletedEventHandler
        
        '''<remarks/>
        Public Event GetInProgressIssuesCompleted As GetInProgressIssuesCompletedEventHandler
        
        '''<remarks/>
        Public Event GetResolvedIssuesCompleted As GetResolvedIssuesCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTotalIssues", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTotalIssues() As Integer
            Dim results() As Object = Me.Invoke("GetTotalIssues", New Object(-1) {})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetTotalIssuesAsync()
            Me.GetTotalIssuesAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetTotalIssuesAsync(ByVal userState As Object)
            If (Me.GetTotalIssuesOperationCompleted Is Nothing) Then
                Me.GetTotalIssuesOperationCompleted = AddressOf Me.OnGetTotalIssuesOperationCompleted
            End If
            Me.InvokeAsync("GetTotalIssues", New Object(-1) {}, Me.GetTotalIssuesOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetTotalIssuesOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetTotalIssuesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetTotalIssuesCompleted(Me, New GetTotalIssuesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPendingIssues", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetPendingIssues() As Integer
            Dim results() As Object = Me.Invoke("GetPendingIssues", New Object(-1) {})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetPendingIssuesAsync()
            Me.GetPendingIssuesAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetPendingIssuesAsync(ByVal userState As Object)
            If (Me.GetPendingIssuesOperationCompleted Is Nothing) Then
                Me.GetPendingIssuesOperationCompleted = AddressOf Me.OnGetPendingIssuesOperationCompleted
            End If
            Me.InvokeAsync("GetPendingIssues", New Object(-1) {}, Me.GetPendingIssuesOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetPendingIssuesOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetPendingIssuesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetPendingIssuesCompleted(Me, New GetPendingIssuesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInProgressIssues", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetInProgressIssues() As Integer
            Dim results() As Object = Me.Invoke("GetInProgressIssues", New Object(-1) {})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetInProgressIssuesAsync()
            Me.GetInProgressIssuesAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetInProgressIssuesAsync(ByVal userState As Object)
            If (Me.GetInProgressIssuesOperationCompleted Is Nothing) Then
                Me.GetInProgressIssuesOperationCompleted = AddressOf Me.OnGetInProgressIssuesOperationCompleted
            End If
            Me.InvokeAsync("GetInProgressIssues", New Object(-1) {}, Me.GetInProgressIssuesOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetInProgressIssuesOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetInProgressIssuesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetInProgressIssuesCompleted(Me, New GetInProgressIssuesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetResolvedIssues", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetResolvedIssues() As Integer
            Dim results() As Object = Me.Invoke("GetResolvedIssues", New Object(-1) {})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetResolvedIssuesAsync()
            Me.GetResolvedIssuesAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetResolvedIssuesAsync(ByVal userState As Object)
            If (Me.GetResolvedIssuesOperationCompleted Is Nothing) Then
                Me.GetResolvedIssuesOperationCompleted = AddressOf Me.OnGetResolvedIssuesOperationCompleted
            End If
            Me.InvokeAsync("GetResolvedIssues", New Object(-1) {}, Me.GetResolvedIssuesOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetResolvedIssuesOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetResolvedIssuesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetResolvedIssuesCompleted(Me, New GetResolvedIssuesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")>  _
    Public Delegate Sub GetTotalIssuesCompletedEventHandler(ByVal sender As Object, ByVal e As GetTotalIssuesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetTotalIssuesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")>  _
    Public Delegate Sub GetPendingIssuesCompletedEventHandler(ByVal sender As Object, ByVal e As GetPendingIssuesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetPendingIssuesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")>  _
    Public Delegate Sub GetInProgressIssuesCompletedEventHandler(ByVal sender As Object, ByVal e As GetInProgressIssuesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetInProgressIssuesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")>  _
    Public Delegate Sub GetResolvedIssuesCompletedEventHandler(ByVal sender As Object, ByVal e As GetResolvedIssuesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetResolvedIssuesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
End Namespace
